baseURL = "https://karolineklan.github.io/CSS_Final_Project_Group9/"
title = "The Food Items Network"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Karoline Klan Hansen", "Kristoffer Helms Kjaer", "Jacob Seerup"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com/drive/folders/1AuX2D92FGSTjIBpWor3D7acklpOoaa6C?usp=sharing"
    github = "https://github.com/KarolineKlan/CSS_Final_Project_Group9"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

